# Generated by Django 3.2 on 2021-04-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='image',
            field=models.CharField(default='imagelink', max_length=255),
            preserve_default=False,
        ),
    ]
